--// Skill Book Icons
--// An Exhilaratingly Organized Literature Mod, Workshop 2071347174 - Original icons
--// aspctt - 11.08.2026
--// Gives every skill book an icon of its own, coloured by the skill it teaches, so a
--// shelf of books can be read at a glance instead of by hovering each one.
--//
--// Build 42 draws ten of the twenty four skill book families with a single shared
--// sprite, Book_Generic, tinted through a colour mask: Blacksmith, Butchering, Carving,
--// FlintKnapping, Glassmaking, LongBlade, Masonry, Pottery, Tailoring and Tracking are
--// all the same picture. Carpentry and Maintenance both use Book8. That is what this is
--// for.
--//
--// Only the icons are taken from the original mod. Its other half, renaming every book
--// and map so they sort into groups, is obsolete: build 42 files literature under
--// DisplayCategory SkillBook, RecipeResource, Literature, Gardening, Junk and Memento by
--// itself, and already names the books "Carpentry I", "Masonry I" and so on, so they
--// group correctly without help. The original forced that ordering by prefixing every
--// name with a space, which on build 42 would only add stray spaces.
--//
--// The set shipped eleven families and build 42 has twenty four, so the missing thirteen
--// were generated by recolouring the originals. See tools/generate_book_icons.py.
--//
--// Shared rather than client, so a multiplayer server and its clients hold the same item
--// definitions.

--// Tuning
-- Item ids are Base.Book<Family><Volume>, and every family runs one to five in this
-- build. Icons are common/media/textures/Item_QolcBook<Family><Volume>.png, which is how
-- the game resolves an Icon value.
local ICON_PREFIX = "QolcBook"
local ITEM_PREFIX = "Base.Book"
local VOLUMES = 5

-- Sorted the way the books read on a shelf rather than by line length, because this is a
-- list of the game's skills and finding one in it matters more here.
local FAMILIES = {
	"Aiming", "Blacksmith", "Butchering", "Carpentry", "Carving", "Cooking",
	"Electrician", "Farming", "FirstAid", "Fishing", "FlintKnapping", "Foraging",
	"Glassmaking", "Husbandry", "LongBlade", "Maintenance", "Masonry", "Mechanic",
	"MetalWelding", "Pottery", "Reloading", "Tailoring", "Tracking", "Trapping"
}

-- A texture with nothing in it, which is what stops vanilla's tint being painted over
-- these icons.
--
-- UIElement.DrawItemIcon draws the icon and then, when the item has a colour mask, draws
-- that mask over the top in the item's own colour. Our icons already carry their colour,
-- so that second pass has to go. It cannot be turned off by blanking the name:
-- InventoryItem.setTextureColorMask falls back to the question mark texture when the name
-- does not resolve, so it has to point at something real and empty.
--
-- Applied to every family, not only the ten that carry a mask today. Setting one where
-- there was none costs a draw of nothing, and it means a book the game starts tinting in
-- a later build is already covered.
local NO_TINT = ICON_PREFIX .. "NoTint"

--// Functions
local function Apply(Item, Icon)
	if Item:getIcon() ~= Icon then Item:DoParam("Icon = " .. Icon) end

	-- No getter for this one, it is a private field, so it is written every time rather
	-- than compared first
	Item:DoParam("IconColorMask = " .. NO_TINT)
end

local function OnInitGlobalModData()
	if not ScriptManager or not ScriptManager.instance then return end

	local Missing = 0

	for _, Family in ipairs(FAMILIES) do
		for Volume = 1, VOLUMES do
			local Name = ITEM_PREFIX .. Family .. tostring(Volume)
			local Item = ScriptManager.instance:getItem(Name)

			-- A missing book means the base game renamed or removed it, which is worth
			-- knowing about rather than silently skipping
			if not Item then
				Missing = Missing + 1
				print("QoL Compendium: skill book not found, " .. Name)
			else
				Apply(Item, ICON_PREFIX .. Family .. tostring(Volume))
			end
		end
	end

	if Missing > 0 then
		print("QoL Compendium: " .. tostring(Missing) .. " skill book icons had no item to attach to")
	end
end

--// Connections
Events.OnInitGlobalModData.Add(OnInitGlobalModData)
